sudo: required

cache: pip

language: python

python:
  - "2.7"

services:
  - postgresql
  - docker

install:
  - pip install tox-travis
  - pip install codecov
  - pip install codeclimate-test-reporter

before_script:
  - psql -c "CREATE DATABASE alfresco;" -U postgres
  - psql -c "CREATE USER alfresco WITH PASSWORD 'alfresco';" -U postgres
  - docker-compose up -d
  - until $(curl -sSf http://localhost:8080/alfresco  -o /dev/null); printf '.' & do sleep 5 ; done
  - wget http://localhost:8080/alfresco/api/-default-/cmis/versions/1.1/browser --password=admin --user=admin

script:
  - tox

after_success:
  - codecov
  - codeclimate-test-reporter

